/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package myapp.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PhysicalWindow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3328226248235732403L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhysicalWindow\",\"namespace\":\"myapp.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"double\"},{\"name\":\"size\",\"type\":\"int\"},{\"name\":\"hoppingSize\",\"type\":\"int\"},{\"name\":\"actualRecords\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PhysicalWindow> ENCODER =
      new BinaryMessageEncoder<PhysicalWindow>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PhysicalWindow> DECODER =
      new BinaryMessageDecoder<PhysicalWindow>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PhysicalWindow> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PhysicalWindow> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PhysicalWindow> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PhysicalWindow>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PhysicalWindow to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PhysicalWindow from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PhysicalWindow instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PhysicalWindow fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double id;
  @Deprecated public int size;
  @Deprecated public int hoppingSize;
  @Deprecated public int actualRecords;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhysicalWindow() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param size The new value for size
   * @param hoppingSize The new value for hoppingSize
   * @param actualRecords The new value for actualRecords
   */
  public PhysicalWindow(java.lang.Double id, java.lang.Integer size, java.lang.Integer hoppingSize, java.lang.Integer actualRecords) {
    this.id = id;
    this.size = size;
    this.hoppingSize = hoppingSize;
    this.actualRecords = actualRecords;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return size;
    case 2: return hoppingSize;
    case 3: return actualRecords;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Double)value$; break;
    case 1: size = (java.lang.Integer)value$; break;
    case 2: hoppingSize = (java.lang.Integer)value$; break;
    case 3: actualRecords = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public double getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(double value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'size' field.
   * @return The value of the 'size' field.
   */
  public int getSize() {
    return size;
  }


  /**
   * Sets the value of the 'size' field.
   * @param value the value to set.
   */
  public void setSize(int value) {
    this.size = value;
  }

  /**
   * Gets the value of the 'hoppingSize' field.
   * @return The value of the 'hoppingSize' field.
   */
  public int getHoppingSize() {
    return hoppingSize;
  }


  /**
   * Sets the value of the 'hoppingSize' field.
   * @param value the value to set.
   */
  public void setHoppingSize(int value) {
    this.hoppingSize = value;
  }

  /**
   * Gets the value of the 'actualRecords' field.
   * @return The value of the 'actualRecords' field.
   */
  public int getActualRecords() {
    return actualRecords;
  }


  /**
   * Sets the value of the 'actualRecords' field.
   * @param value the value to set.
   */
  public void setActualRecords(int value) {
    this.actualRecords = value;
  }

  public void increaseActualRecords(int value){this.actualRecords += value;}

  /**
   * Creates a new PhysicalWindow RecordBuilder.
   * @return A new PhysicalWindow RecordBuilder
   */
  public static myapp.avro.PhysicalWindow.Builder newBuilder() {
    return new myapp.avro.PhysicalWindow.Builder();
  }

  /**
   * Creates a new PhysicalWindow RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhysicalWindow RecordBuilder
   */
  public static myapp.avro.PhysicalWindow.Builder newBuilder(myapp.avro.PhysicalWindow.Builder other) {
    if (other == null) {
      return new myapp.avro.PhysicalWindow.Builder();
    } else {
      return new myapp.avro.PhysicalWindow.Builder(other);
    }
  }

  /**
   * Creates a new PhysicalWindow RecordBuilder by copying an existing PhysicalWindow instance.
   * @param other The existing instance to copy.
   * @return A new PhysicalWindow RecordBuilder
   */
  public static myapp.avro.PhysicalWindow.Builder newBuilder(myapp.avro.PhysicalWindow other) {
    if (other == null) {
      return new myapp.avro.PhysicalWindow.Builder();
    } else {
      return new myapp.avro.PhysicalWindow.Builder(other);
    }
  }

  /**
   * RecordBuilder for PhysicalWindow instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhysicalWindow>
    implements org.apache.avro.data.RecordBuilder<PhysicalWindow> {

    private double id;
    private int size;
    private int hoppingSize;
    private int actualRecords;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(myapp.avro.PhysicalWindow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.size)) {
        this.size = data().deepCopy(fields()[1].schema(), other.size);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.hoppingSize)) {
        this.hoppingSize = data().deepCopy(fields()[2].schema(), other.hoppingSize);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.actualRecords)) {
        this.actualRecords = data().deepCopy(fields()[3].schema(), other.actualRecords);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing PhysicalWindow instance
     * @param other The existing instance to copy.
     */
    private Builder(myapp.avro.PhysicalWindow other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.size)) {
        this.size = data().deepCopy(fields()[1].schema(), other.size);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.hoppingSize)) {
        this.hoppingSize = data().deepCopy(fields()[2].schema(), other.hoppingSize);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.actualRecords)) {
        this.actualRecords = data().deepCopy(fields()[3].schema(), other.actualRecords);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public double getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder setId(double value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'size' field.
      * @return The value.
      */
    public int getSize() {
      return size;
    }


    /**
      * Sets the value of the 'size' field.
      * @param value The value of 'size'.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder setSize(int value) {
      validate(fields()[1], value);
      this.size = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'size' field has been set.
      * @return True if the 'size' field has been set, false otherwise.
      */
    public boolean hasSize() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'size' field.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder clearSize() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'hoppingSize' field.
      * @return The value.
      */
    public int getHoppingSize() {
      return hoppingSize;
    }


    /**
      * Sets the value of the 'hoppingSize' field.
      * @param value The value of 'hoppingSize'.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder setHoppingSize(int value) {
      validate(fields()[2], value);
      this.hoppingSize = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'hoppingSize' field has been set.
      * @return True if the 'hoppingSize' field has been set, false otherwise.
      */
    public boolean hasHoppingSize() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'hoppingSize' field.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder clearHoppingSize() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'actualRecords' field.
      * @return The value.
      */
    public int getActualRecords() {
      return actualRecords;
    }


    /**
      * Sets the value of the 'actualRecords' field.
      * @param value The value of 'actualRecords'.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder setActualRecords(int value) {
      validate(fields()[3], value);
      this.actualRecords = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'actualRecords' field has been set.
      * @return True if the 'actualRecords' field has been set, false otherwise.
      */
    public boolean hasActualRecords() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'actualRecords' field.
      * @return This builder.
      */
    public myapp.avro.PhysicalWindow.Builder clearActualRecords() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PhysicalWindow build() {
      try {
        PhysicalWindow record = new PhysicalWindow();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Double) defaultValue(fields()[0]);
        record.size = fieldSetFlags()[1] ? this.size : (java.lang.Integer) defaultValue(fields()[1]);
        record.hoppingSize = fieldSetFlags()[2] ? this.hoppingSize : (java.lang.Integer) defaultValue(fields()[2]);
        record.actualRecords = fieldSetFlags()[3] ? this.actualRecords : (java.lang.Integer) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PhysicalWindow>
    WRITER$ = (org.apache.avro.io.DatumWriter<PhysicalWindow>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PhysicalWindow>
    READER$ = (org.apache.avro.io.DatumReader<PhysicalWindow>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.id);

    out.writeInt(this.size);

    out.writeInt(this.hoppingSize);

    out.writeInt(this.actualRecords);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readDouble();

      this.size = in.readInt();

      this.hoppingSize = in.readInt();

      this.actualRecords = in.readInt();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readDouble();
          break;

        case 1:
          this.size = in.readInt();
          break;

        case 2:
          this.hoppingSize = in.readInt();
          break;

        case 3:
          this.actualRecords = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










